Repository Alvarado007/Primer-miniproyecto-java, pull requests merged in 2025-04, with the labels that each got.

#1 creacion clase ataque
  src/Clases/Ataque.java
  src/Enums/TipoDano.java
Labels: create new class

#2 Se crea la clase Entrenador con sus atributos como nombre y equipo co…
  src/Clases/Entrenador.java
Labels: create new class

#3 se crea una nueva funcionalidad onde voya tener una relacion de compo…
  src/Clases/Pokemon.java
Labels: enhancement

#4 Se ajustan nombres de variables y se crea la variable tipoAtaque se a…
  src/Clases/Ataque.java
Labels: Fixes

#5 Ajuste clase visualizacion
  src/App.java
  src/Clases/Pokemon.java
  src/Clases/Visualizacion.java
Labels: enhancement

#6 implementacion de random y ajustes de codigo
  src/Clases/Ataque.java
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Clases/Visualizacion.java
Labels: enhancement

#7 Se modifican algunos métodos para mejor interpretación para el usuario
  src/Clases/Entrenador.java
  src/Clases/Visualizacion.java
Labels: Fixes

#10 Se agrega la funcionalidad de ventaja de tipos en los ataques
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Clases/Visualizacion.java
Labels: enhancement

#11 cambios en el readmi en la grafica de relacion de las clases
  README.md
Labels: documentation

#12 Optimización del código
  src/Clases/Entrenador.java
  src/Clases/Visualizacion.java
Labels: Fixes
